#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// HarshDoorstop
// 4.25.4-0+++UE4+Release-4.25

// Includes the entire SDK, include files directly for faster compilation!

#include "SDK/Basic.hpp"
#include "SDK/CoreUObject_structs.hpp"
#include "SDK/CoreUObject_classes.hpp"
#include "SDK/PacketHandler_classes.hpp"
#include "SDK/InputCore_structs.hpp"
#include "SDK/Slate_structs.hpp"
#include "SDK/PhysicsCore_structs.hpp"
#include "SDK/Engine_structs.hpp"
#include "SDK/AudioPlatformConfiguration_structs.hpp"
#include "SDK/SlateCore_structs.hpp"
#include "SDK/Engine_classes.hpp"
#include "SDK/OnlineSubsystemUtils_classes.hpp"
#include "SDK/DonkehFramework_structs.hpp"
#include "SDK/MovieScene_structs.hpp"
#include "SDK/DonkehFramework_classes.hpp"
#include "SDK/AIModule_classes.hpp"
#include "SDK/NavigationSystem_classes.hpp"
#include "SDK/MovieScene_classes.hpp"
#include "SDK/UMG_classes.hpp"
#include "SDK/DonkehFrameworkUI_classes.hpp"
#include "SDK/DonkehFrameworkAnim_classes.hpp"
#include "SDK/DonkehFrameworkComms_structs.hpp"
#include "SDK/HDMain_structs.hpp"
#include "SDK/HDMain_classes.hpp"
#include "SDK/Tinkerbox_structs.hpp"
#include "SDK/Tinkerbox_classes.hpp"
#include "SDK/HDCoreUGC_structs.hpp"
#include "SDK/HDCoreUGC_classes.hpp"
#include "SDK/GOAPNPC_classes.hpp"
#include "SDK/ArcVehicles_structs.hpp"
#include "SDK/ArcVehicles_classes.hpp"
#include "SDK/SlateCore_classes.hpp"
#include "SDK/InputCore_classes.hpp"
#include "SDK/Slate_classes.hpp"
#include "SDK/MovieSceneTracks_classes.hpp"
#include "SDK/BP_HDPlayerCharacterBase_classes.hpp"

