#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DonkehFrameworkUI

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// Enum DonkehFrameworkUI.EMenuActivationMode
// NumValues: 0x0004
enum class EMenuActivationMode : uint8
{
	Transparent                              = 0,
	Opaque                                   = 1,
	Exclusive                                = 2,
	EMenuActivationMode_MAX                  = 3,
};

// Enum DonkehFrameworkUI.EDFUIMessagingResult
// NumValues: 0x0006
enum class EDFUIMessagingResult : uint8
{
	Confirmed                                = 0,
	Declined                                 = 1,
	Cancelled                                = 2,
	Killed                                   = 3,
	Unknown                                  = 4,
	EDFUIMessagingResult_MAX                 = 5,
};

// ScriptStruct DonkehFrameworkUI.DFConfirmationDialogAction
// 0x0020 (0x0020 - 0x0000)
struct FDFConfirmationDialogAction final 
{
public:
	EDFUIMessagingResult                          Result;                                            // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_10D6[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   OptionalDisplayText;                               // 0x0008(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
};
static_assert(alignof(FDFConfirmationDialogAction) == 0x000008, "Wrong alignment on FDFConfirmationDialogAction");
static_assert(sizeof(FDFConfirmationDialogAction) == 0x000020, "Wrong size on FDFConfirmationDialogAction");
static_assert(offsetof(FDFConfirmationDialogAction, Result) == 0x000000, "Member 'FDFConfirmationDialogAction::Result' has a wrong offset!");
static_assert(offsetof(FDFConfirmationDialogAction, OptionalDisplayText) == 0x000008, "Member 'FDFConfirmationDialogAction::OptionalDisplayText' has a wrong offset!");

// ScriptStruct DonkehFrameworkUI.MenuStackEntry
// 0x0010 (0x0010 - 0x0000)
struct FMenuStackEntry final 
{
public:
	class UDFBaseMenu*                            Menu;                                              // 0x0000(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMenuActivationMode                           ActivationMode;                                    // 0x0008(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShowMouseCursor;                                  // 0x0009(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUIOnlyInput;                                      // 0x000A(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_10D7[0x5];                                     // 0x000B(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FMenuStackEntry) == 0x000008, "Wrong alignment on FMenuStackEntry");
static_assert(sizeof(FMenuStackEntry) == 0x000010, "Wrong size on FMenuStackEntry");
static_assert(offsetof(FMenuStackEntry, Menu) == 0x000000, "Member 'FMenuStackEntry::Menu' has a wrong offset!");
static_assert(offsetof(FMenuStackEntry, ActivationMode) == 0x000008, "Member 'FMenuStackEntry::ActivationMode' has a wrong offset!");
static_assert(offsetof(FMenuStackEntry, bShowMouseCursor) == 0x000009, "Member 'FMenuStackEntry::bShowMouseCursor' has a wrong offset!");
static_assert(offsetof(FMenuStackEntry, bUIOnlyInput) == 0x00000A, "Member 'FMenuStackEntry::bUIOnlyInput' has a wrong offset!");

// ScriptStruct DonkehFrameworkUI.MinimapPOITableRow
// 0x0128 (0x0130 - 0x0008)
struct FMinimapPOITableRow final  : public FTableRowBase
{
public:
	TSoftClassPtr<class UClass>                   ActorClass;                                        // 0x0008(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, NoClear, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bMatchChildClasses : 1;                            // 0x0030(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_10D8[0x7];                                     // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftClassPtr<class UClass>                   ToolTipWidgetClass;                                // 0x0038(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftClassPtr<class UClass>                   WidgetClass;                                       // 0x0060(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, NoClear, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSlateBrush                            IconBrush;                                         // 0x0088(0x0088)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	class FText                                   ToolTipText;                                       // 0x0110(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	uint8                                         bSelectable : 1;                                   // 0x0128(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bDynamic : 1;                                      // 0x0128(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bFixedRotation : 1;                                // 0x0128(0x0001)(BitIndex: 0x02, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_10D9[0x7];                                     // 0x0129(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FMinimapPOITableRow) == 0x000008, "Wrong alignment on FMinimapPOITableRow");
static_assert(sizeof(FMinimapPOITableRow) == 0x000130, "Wrong size on FMinimapPOITableRow");
static_assert(offsetof(FMinimapPOITableRow, ActorClass) == 0x000008, "Member 'FMinimapPOITableRow::ActorClass' has a wrong offset!");
static_assert(offsetof(FMinimapPOITableRow, ToolTipWidgetClass) == 0x000038, "Member 'FMinimapPOITableRow::ToolTipWidgetClass' has a wrong offset!");
static_assert(offsetof(FMinimapPOITableRow, WidgetClass) == 0x000060, "Member 'FMinimapPOITableRow::WidgetClass' has a wrong offset!");
static_assert(offsetof(FMinimapPOITableRow, IconBrush) == 0x000088, "Member 'FMinimapPOITableRow::IconBrush' has a wrong offset!");
static_assert(offsetof(FMinimapPOITableRow, ToolTipText) == 0x000110, "Member 'FMinimapPOITableRow::ToolTipText' has a wrong offset!");

}

