#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MovieScene

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "MovieScene_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// Class MovieScene.MovieSceneSignedObject
// 0x0028 (0x0050 - 0x0028)
class UMovieSceneSignedObject : public UObject
{
public:
	struct FGuid                                  Signature;                                         // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_13AE[0x18];                                    // 0x0038(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneSignedObject">();
	}
	static class UMovieSceneSignedObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneSignedObject>();
	}
};
//(alignof(UMovieSceneSignedObject) == 0x000008, "Wrong alignment on UMovieSceneSignedObject");
//(sizeof(UMovieSceneSignedObject) == 0x000050, "Wrong size on UMovieSceneSignedObject");
//(offsetof(UMovieSceneSignedObject, Signature) == 0x000028, "Member 'UMovieSceneSignedObject::Signature' has a wrong offset!");

// Class MovieScene.MovieSceneSection
// 0x0090 (0x00E0 - 0x0050)
class UMovieSceneSection : public UMovieSceneSignedObject
{
public:
	struct FMovieSceneSectionEvalOptions          EvalOptions;                                       // 0x0050(0x0002)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_13AF[0x6];                                     // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMovieSceneEasingSettings              Easing;                                            // 0x0058(0x0038)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	struct FMovieSceneFrameRange                  SectionRange;                                      // 0x0090(0x0010)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	struct FFrameNumber                           PreRollFrames;                                     // 0x00A0(0x0004)(Edit, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FFrameNumber                           PostRollFrames;                                    // 0x00A4(0x0004)(Edit, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         RowIndex;                                          // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         OverlapPriority;                                   // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         bIsActive : 1;                                     // 0x00B0(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate))
	uint8                                         bIsLocked : 1;                                     // 0x00B0(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate))
	uint8                                         Pad_13B0[0x3];                                     // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StartTime;                                         // 0x00B4(0x0004)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         EndTime;                                           // 0x00B8(0x0004)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         PrerollTime;                                       // 0x00BC(0x0004)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         PostrollTime;                                      // 0x00C0(0x0004)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         bIsInfinite : 1;                                   // 0x00C4(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Deprecated, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected))
	uint8                                         Pad_13B1[0x3];                                     // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bSupportsInfiniteRange;                            // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FOptionalMovieSceneBlendType           BlendType;                                         // 0x00C9(0x0002)(NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_13B2[0x15];                                    // 0x00CB(0x0015)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetBlendType(EMovieSceneBlendType InBlendType);
	void SetCompletionMode(EMovieSceneCompletionMode InCompletionMode);
	void SetIsActive(bool bInIsActive);
	void SetIsLocked(bool bInIsLocked);
	void SetOverlapPriority(int32 NewPriority);
	void SetPostRollFrames(int32 InPostRollFrames);
	void SetPreRollFrames(int32 InPreRollFrames);
	void SetRowIndex(int32 NewRowIndex);

	struct FOptionalMovieSceneBlendType GetBlendType() const;
	EMovieSceneCompletionMode GetCompletionMode() const;
	int32 GetOverlapPriority() const;
	int32 GetPostRollFrames() const;
	int32 GetPreRollFrames() const;
	int32 GetRowIndex() const;
	bool IsActive() const;
	bool IsLocked() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneSection">();
	}
	static class UMovieSceneSection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneSection>();
	}
};
//(alignof(UMovieSceneSection) == 0x000008, "Wrong alignment on UMovieSceneSection");
//(sizeof(UMovieSceneSection) == 0x0000E0, "Wrong size on UMovieSceneSection");
//(offsetof(UMovieSceneSection, EvalOptions) == 0x000050, "Member 'UMovieSceneSection::EvalOptions' has a wrong offset!");
//(offsetof(UMovieSceneSection, Easing) == 0x000058, "Member 'UMovieSceneSection::Easing' has a wrong offset!");
//(offsetof(UMovieSceneSection, SectionRange) == 0x000090, "Member 'UMovieSceneSection::SectionRange' has a wrong offset!");
//(offsetof(UMovieSceneSection, PreRollFrames) == 0x0000A0, "Member 'UMovieSceneSection::PreRollFrames' has a wrong offset!");
//(offsetof(UMovieSceneSection, PostRollFrames) == 0x0000A4, "Member 'UMovieSceneSection::PostRollFrames' has a wrong offset!");
//(offsetof(UMovieSceneSection, RowIndex) == 0x0000A8, "Member 'UMovieSceneSection::RowIndex' has a wrong offset!");
//(offsetof(UMovieSceneSection, OverlapPriority) == 0x0000AC, "Member 'UMovieSceneSection::OverlapPriority' has a wrong offset!");
//(offsetof(UMovieSceneSection, StartTime) == 0x0000B4, "Member 'UMovieSceneSection::StartTime' has a wrong offset!");
//(offsetof(UMovieSceneSection, EndTime) == 0x0000B8, "Member 'UMovieSceneSection::EndTime' has a wrong offset!");
//(offsetof(UMovieSceneSection, PrerollTime) == 0x0000BC, "Member 'UMovieSceneSection::PrerollTime' has a wrong offset!");
//(offsetof(UMovieSceneSection, PostrollTime) == 0x0000C0, "Member 'UMovieSceneSection::PostrollTime' has a wrong offset!");
//(offsetof(UMovieSceneSection, bSupportsInfiniteRange) == 0x0000C8, "Member 'UMovieSceneSection::bSupportsInfiniteRange' has a wrong offset!");
//(offsetof(UMovieSceneSection, BlendType) == 0x0000C9, "Member 'UMovieSceneSection::BlendType' has a wrong offset!");

// Class MovieScene.MovieSceneSubSection
// 0x0078 (0x0158 - 0x00E0)
class UMovieSceneSubSection : public UMovieSceneSection
{
public:
	struct FMovieSceneSectionParameters           Parameters;                                        // 0x00E0(0x0024)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	float                                         StartOffset;                                       // 0x0104(0x0004)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         TimeScale;                                         // 0x0108(0x0004)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         PrerollTime_MovieSceneSubSection;                  // 0x010C(0x0004)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UMovieSceneSequence*                    SubSequence;                                       // 0x0110(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TLazyObjectPtr<class AActor>                  ActorToRecord;                                     // 0x0118(0x001C)(Edit, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_13B3[0x4];                                     // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 TargetSequenceName;                                // 0x0138(0x0010)(Edit, ZeroConstructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FDirectoryPath                         TargetPathToRecordTo;                              // 0x0148(0x0010)(Edit, Protected, NativeAccessSpecifierProtected)

public:
	void SetSequence(class UMovieSceneSequence* Sequence);

	class UMovieSceneSequence* GetSequence() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneSubSection">();
	}
	static class UMovieSceneSubSection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneSubSection>();
	}
};
//(alignof(UMovieSceneSubSection) == 0x000008, "Wrong alignment on UMovieSceneSubSection");
//(sizeof(UMovieSceneSubSection) == 0x000158, "Wrong size on UMovieSceneSubSection");
//(offsetof(UMovieSceneSubSection, Parameters) == 0x0000E0, "Member 'UMovieSceneSubSection::Parameters' has a wrong offset!");
//(offsetof(UMovieSceneSubSection, StartOffset) == 0x000104, "Member 'UMovieSceneSubSection::StartOffset' has a wrong offset!");
//(offsetof(UMovieSceneSubSection, TimeScale) == 0x000108, "Member 'UMovieSceneSubSection::TimeScale' has a wrong offset!");
//(offsetof(UMovieSceneSubSection, PrerollTime_MovieSceneSubSection) == 0x00010C, "Member 'UMovieSceneSubSection::PrerollTime_MovieSceneSubSection' has a wrong offset!");
//(offsetof(UMovieSceneSubSection, SubSequence) == 0x000110, "Member 'UMovieSceneSubSection::SubSequence' has a wrong offset!");
//(offsetof(UMovieSceneSubSection, ActorToRecord) == 0x000118, "Member 'UMovieSceneSubSection::ActorToRecord' has a wrong offset!");
//(offsetof(UMovieSceneSubSection, TargetSequenceName) == 0x000138, "Member 'UMovieSceneSubSection::TargetSequenceName' has a wrong offset!");
//(offsetof(UMovieSceneSubSection, TargetPathToRecordTo) == 0x000148, "Member 'UMovieSceneSubSection::TargetPathToRecordTo' has a wrong offset!");

// Class MovieScene.MovieSceneSequencePlayer
// 0x0860 (0x0888 - 0x0028)
class UMovieSceneSequencePlayer : public UObject
{
public:
	uint8                                         Pad_13B4[0x3E0];                                   // 0x0028(0x03E0)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnPlay;                                            // 0x0408(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnPlayReverse;                                     // 0x0418(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnStop;                                            // 0x0428(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnPause;                                           // 0x0438(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnFinished;                                        // 0x0448(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	EMovieScenePlayerStatus                       Status;                                            // 0x0458(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_13B5[0x3];                                     // 0x0459(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	uint8                                         bReversePlayback : 1;                              // 0x045C(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Net, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected))
	uint8                                         Pad_13B6[0x3];                                     // 0x045D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMovieSceneSequence*                    Sequence;                                          // 0x0460(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FFrameNumber                           StartTime;                                         // 0x0468(0x0004)(Net, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         DurationFrames;                                    // 0x046C(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         CurrentNumLoops;                                   // 0x0470(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_13B7[0x14];                                    // 0x0474(0x0014)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMovieSceneSequencePlaybackSettings    PlaybackSettings;                                  // 0x0488(0x0014)(Net, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_13B8[0x4];                                     // 0x049C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMovieSceneRootEvaluationTemplateInstance RootTemplateInstance;                              // 0x04A0(0x0320)(Transient, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_13B9[0x68];                                    // 0x07C0(0x0068)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMovieSceneSequenceReplProperties      NetSyncProps;                                      // 0x0828(0x0010)(Net, NoDestructor, Protected, NativeAccessSpecifierProtected)
	TScriptInterface<class IMovieScenePlaybackClient> PlaybackClient;                                    // 0x0838(0x0010)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	uint8                                         Pad_13BA[0x40];                                    // 0x0848(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ChangePlaybackDirection();
	TArray<class UObject*> GetBoundObjects(const struct FMovieSceneObjectBindingID& ObjectBinding);
	bool GetDisableCameraCuts();
	TArray<struct FMovieSceneObjectBindingID> GetObjectBindings(class UObject* InObject);
	void GoToEndAndStop();
	void JumpToFrame(const struct FFrameTime& NewPosition);
	bool JumpToMarkedFrame(const class FString& InLabel);
	void JumpToPosition(float NewPlaybackPosition);
	void JumpToSeconds(float TimeInSeconds);
	void Pause();
	void Play();
	void PlayLooping(int32 NumLoops);
	void PlayReverse();
	void PlayToFrame(const struct FFrameTime& NewPosition);
	bool PlayToMarkedFrame(const class FString& InLabel);
	void PlayToSeconds(float TimeInSeconds);
	void RPC_ExplicitServerUpdateEvent(EUpdatePositionMethod Method, const struct FFrameTime& RelevantTime);
	void RPC_OnStopEvent(const struct FFrameTime& StoppedTime);
	void Scrub();
	void ScrubToFrame(const struct FFrameTime& NewPosition);
	bool ScrubToMarkedFrame(const class FString& InLabel);
	void ScrubToSeconds(float TimeInSeconds);
	void SetDisableCameraCuts(bool bInDisableCameraCuts);
	void SetFrameRange(int32 StartFrame, int32 Duration);
	void SetFrameRate(const struct FFrameRate& FrameRate);
	void SetPlaybackPosition(float NewPlaybackPosition);
	void SetPlaybackRange(float NewStartTime, float NewEndTime);
	void SetPlayRate(float PlayRate);
	void SetTimeRange(float Param_StartTime, float Duration);
	void Stop();
	void StopAtCurrentTime();

	struct FQualifiedFrameTime GetCurrentTime() const;
	struct FQualifiedFrameTime GetDuration() const;
	struct FQualifiedFrameTime GetEndTime() const;
	int32 GetFrameDuration() const;
	struct FFrameRate GetFrameRate() const;
	float GetLength() const;
	float GetPlaybackEnd() const;
	float GetPlaybackPosition() const;
	float GetPlaybackStart() const;
	float GetPlayRate() const;
	struct FQualifiedFrameTime GetStartTime() const;
	bool IsPaused() const;
	bool IsPlaying() const;
	bool IsReversed() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneSequencePlayer">();
	}
	static class UMovieSceneSequencePlayer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneSequencePlayer>();
	}
};
//(alignof(UMovieSceneSequencePlayer) == 0x000008, "Wrong alignment on UMovieSceneSequencePlayer");
//(sizeof(UMovieSceneSequencePlayer) == 0x000888, "Wrong size on UMovieSceneSequencePlayer");
//(offsetof(UMovieSceneSequencePlayer, OnPlay) == 0x000408, "Member 'UMovieSceneSequencePlayer::OnPlay' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, OnPlayReverse) == 0x000418, "Member 'UMovieSceneSequencePlayer::OnPlayReverse' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, OnStop) == 0x000428, "Member 'UMovieSceneSequencePlayer::OnStop' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, OnPause) == 0x000438, "Member 'UMovieSceneSequencePlayer::OnPause' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, OnFinished) == 0x000448, "Member 'UMovieSceneSequencePlayer::OnFinished' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, Status) == 0x000458, "Member 'UMovieSceneSequencePlayer::Status' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, Sequence) == 0x000460, "Member 'UMovieSceneSequencePlayer::Sequence' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, StartTime) == 0x000468, "Member 'UMovieSceneSequencePlayer::StartTime' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, DurationFrames) == 0x00046C, "Member 'UMovieSceneSequencePlayer::DurationFrames' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, CurrentNumLoops) == 0x000470, "Member 'UMovieSceneSequencePlayer::CurrentNumLoops' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, PlaybackSettings) == 0x000488, "Member 'UMovieSceneSequencePlayer::PlaybackSettings' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, RootTemplateInstance) == 0x0004A0, "Member 'UMovieSceneSequencePlayer::RootTemplateInstance' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, NetSyncProps) == 0x000828, "Member 'UMovieSceneSequencePlayer::NetSyncProps' has a wrong offset!");
//(offsetof(UMovieSceneSequencePlayer, PlaybackClient) == 0x000838, "Member 'UMovieSceneSequencePlayer::PlaybackClient' has a wrong offset!");

// Class MovieScene.MovieScene
// 0x00F8 (0x0148 - 0x0050)
class UMovieScene final  : public UMovieSceneSignedObject
{
public:
	TArray<struct FMovieSceneSpawnable>           Spawnables;                                        // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<struct FMovieScenePossessable>         Possessables;                                      // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<struct FMovieSceneBinding>             ObjectBindings;                                    // 0x0070(0x0010)(ZeroConstructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TMap<class FName, struct FMovieSceneObjectBindingIDs> BindingGroups;                                     // 0x0080(0x0050)(NativeAccessSpecifierPrivate)
	TArray<class UMovieSceneTrack*>               MasterTracks;                                      // 0x00D0(0x0010)(ExportObject, ZeroConstructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UMovieSceneTrack*                       CameraCutTrack;                                    // 0x00E0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, PersistentInstance, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FMovieSceneFrameRange                  SelectionRange;                                    // 0x00E8(0x0010)(NoDestructor, NativeAccessSpecifierPrivate)
	struct FMovieSceneFrameRange                  PlaybackRange;                                     // 0x00F8(0x0010)(NoDestructor, NativeAccessSpecifierPrivate)
	struct FFrameRate                             TickResolution;                                    // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FFrameRate                             DisplayRate;                                       // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EMovieSceneEvaluationType                     EvaluationType;                                    // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EUpdateClockSource                            ClockSource;                                       // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_13BF[0x6];                                     // 0x011A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftObjectPath                        CustomClockSourcePath;                             // 0x0120(0x0018)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<struct FMovieSceneMarkedFrame>         MarkedFrames;                                      // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieScene">();
	}
	static class UMovieScene* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieScene>();
	}
};
//(alignof(UMovieScene) == 0x000008, "Wrong alignment on UMovieScene");
//(sizeof(UMovieScene) == 0x000148, "Wrong size on UMovieScene");
//(offsetof(UMovieScene, Spawnables) == 0x000050, "Member 'UMovieScene::Spawnables' has a wrong offset!");
//(offsetof(UMovieScene, Possessables) == 0x000060, "Member 'UMovieScene::Possessables' has a wrong offset!");
//(offsetof(UMovieScene, ObjectBindings) == 0x000070, "Member 'UMovieScene::ObjectBindings' has a wrong offset!");
//(offsetof(UMovieScene, BindingGroups) == 0x000080, "Member 'UMovieScene::BindingGroups' has a wrong offset!");
//(offsetof(UMovieScene, MasterTracks) == 0x0000D0, "Member 'UMovieScene::MasterTracks' has a wrong offset!");
//(offsetof(UMovieScene, CameraCutTrack) == 0x0000E0, "Member 'UMovieScene::CameraCutTrack' has a wrong offset!");
//(offsetof(UMovieScene, SelectionRange) == 0x0000E8, "Member 'UMovieScene::SelectionRange' has a wrong offset!");
//(offsetof(UMovieScene, PlaybackRange) == 0x0000F8, "Member 'UMovieScene::PlaybackRange' has a wrong offset!");
//(offsetof(UMovieScene, TickResolution) == 0x000108, "Member 'UMovieScene::TickResolution' has a wrong offset!");
//(offsetof(UMovieScene, DisplayRate) == 0x000110, "Member 'UMovieScene::DisplayRate' has a wrong offset!");
//(offsetof(UMovieScene, EvaluationType) == 0x000118, "Member 'UMovieScene::EvaluationType' has a wrong offset!");
//(offsetof(UMovieScene, ClockSource) == 0x000119, "Member 'UMovieScene::ClockSource' has a wrong offset!");
//(offsetof(UMovieScene, CustomClockSourcePath) == 0x000120, "Member 'UMovieScene::CustomClockSourcePath' has a wrong offset!");
//(offsetof(UMovieScene, MarkedFrames) == 0x000138, "Member 'UMovieScene::MarkedFrames' has a wrong offset!");

// Class MovieScene.TestMovieSceneSection
// 0x0000 (0x00E0 - 0x00E0)
class UTestMovieSceneSection final  : public UMovieSceneSection
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TestMovieSceneSection">();
	}
	static class UTestMovieSceneSection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTestMovieSceneSection>();
	}
};
//(alignof(UTestMovieSceneSection) == 0x000008, "Wrong alignment on UTestMovieSceneSection");
//(sizeof(UTestMovieSceneSection) == 0x0000E0, "Wrong size on UTestMovieSceneSection");

// Class MovieScene.MovieSceneTrack
// 0x0008 (0x0058 - 0x0050)
class UMovieSceneTrack : public UMovieSceneSignedObject
{
public:
	struct FMovieSceneTrackEvalOptions            EvalOptions;                                       // 0x0050(0x0004)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_13C0[0x1];                                     // 0x0054(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bIsEvalDisabled;                                   // 0x0055(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_13C1[0x2];                                     // 0x0056(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneTrack">();
	}
	static class UMovieSceneTrack* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneTrack>();
	}
};
//(alignof(UMovieSceneTrack) == 0x000008, "Wrong alignment on UMovieSceneTrack");
//(sizeof(UMovieSceneTrack) == 0x000058, "Wrong size on UMovieSceneTrack");
//(offsetof(UMovieSceneTrack, EvalOptions) == 0x000050, "Member 'UMovieSceneTrack::EvalOptions' has a wrong offset!");
//(offsetof(UMovieSceneTrack, bIsEvalDisabled) == 0x000055, "Member 'UMovieSceneTrack::bIsEvalDisabled' has a wrong offset!");

// Class MovieScene.MovieSceneSequence
// 0x02F8 (0x0348 - 0x0050)
class UMovieSceneSequence : public UMovieSceneSignedObject
{
public:
	struct FMovieSceneEvaluationTemplate          PrecompiledEvaluationTemplate;                     // 0x0050(0x02F0)(ContainsInstancedReference, NativeAccessSpecifierPublic)
	EMovieSceneCompletionMode                     DefaultCompletionMode;                             // 0x0340(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bParentContextsAreSignificant;                     // 0x0341(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bPlayableDirectly;                                 // 0x0342(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_13C2[0x5];                                     // 0x0343(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	struct FMovieSceneObjectBindingID FindBindingByTag(class FName InBindingName) const;
	const TArray<struct FMovieSceneObjectBindingID> FindBindingsByTag(class FName InBindingName) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneSequence">();
	}
	static class UMovieSceneSequence* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneSequence>();
	}
};
//(alignof(UMovieSceneSequence) == 0x000008, "Wrong alignment on UMovieSceneSequence");
//(sizeof(UMovieSceneSequence) == 0x000348, "Wrong size on UMovieSceneSequence");
//(offsetof(UMovieSceneSequence, PrecompiledEvaluationTemplate) == 0x000050, "Member 'UMovieSceneSequence::PrecompiledEvaluationTemplate' has a wrong offset!");
//(offsetof(UMovieSceneSequence, DefaultCompletionMode) == 0x000340, "Member 'UMovieSceneSequence::DefaultCompletionMode' has a wrong offset!");
//(offsetof(UMovieSceneSequence, bParentContextsAreSignificant) == 0x000341, "Member 'UMovieSceneSequence::bParentContextsAreSignificant' has a wrong offset!");
//(offsetof(UMovieSceneSequence, bPlayableDirectly) == 0x000342, "Member 'UMovieSceneSequence::bPlayableDirectly' has a wrong offset!");

// Class MovieScene.MovieSceneEasingExternalCurve
// 0x0010 (0x0038 - 0x0028)
class UMovieSceneEasingExternalCurve final  : public UObject
{
public:
	uint8                                         Pad_13C3[0x8];                                     // 0x0028(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            Curve;                                             // 0x0030(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneEasingExternalCurve">();
	}
	static class UMovieSceneEasingExternalCurve* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneEasingExternalCurve>();
	}
};
//(alignof(UMovieSceneEasingExternalCurve) == 0x000008, "Wrong alignment on UMovieSceneEasingExternalCurve");
//(sizeof(UMovieSceneEasingExternalCurve) == 0x000038, "Wrong size on UMovieSceneEasingExternalCurve");
//(offsetof(UMovieSceneEasingExternalCurve, Curve) == 0x000030, "Member 'UMovieSceneEasingExternalCurve::Curve' has a wrong offset!");

// Class MovieScene.MovieSceneNameableTrack
// 0x0000 (0x0058 - 0x0058)
class UMovieSceneNameableTrack : public UMovieSceneTrack
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneNameableTrack">();
	}
	static class UMovieSceneNameableTrack* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneNameableTrack>();
	}
};
//(alignof(UMovieSceneNameableTrack) == 0x000008, "Wrong alignment on UMovieSceneNameableTrack");
//(sizeof(UMovieSceneNameableTrack) == 0x000058, "Wrong size on UMovieSceneNameableTrack");

// Class MovieScene.MovieSceneKeyProxy
// 0x0000 (0x0028 - 0x0028)
class IMovieSceneKeyProxy final  : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneKeyProxy">();
	}
	static class IMovieSceneKeyProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<IMovieSceneKeyProxy>();
	}
};
//(alignof(IMovieSceneKeyProxy) == 0x000008, "Wrong alignment on IMovieSceneKeyProxy");
//(sizeof(IMovieSceneKeyProxy) == 0x000028, "Wrong size on IMovieSceneKeyProxy");

// Class MovieScene.MovieSceneSubTrack
// 0x0010 (0x0068 - 0x0058)
class UMovieSceneSubTrack : public UMovieSceneNameableTrack
{
public:
	TArray<class UMovieSceneSection*>             Sections;                                          // 0x0058(0x0010)(ExportObject, ZeroConstructor, ContainsInstancedReference, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneSubTrack">();
	}
	static class UMovieSceneSubTrack* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneSubTrack>();
	}
};
//(alignof(UMovieSceneSubTrack) == 0x000008, "Wrong alignment on UMovieSceneSubTrack");
//(sizeof(UMovieSceneSubTrack) == 0x000068, "Wrong size on UMovieSceneSubTrack");
//(offsetof(UMovieSceneSubTrack, Sections) == 0x000058, "Member 'UMovieSceneSubTrack::Sections' has a wrong offset!");

// Class MovieScene.MovieSceneCustomClockSource
// 0x0000 (0x0028 - 0x0028)
class IMovieSceneCustomClockSource final  : public IInterface
{
public:
	struct FFrameTime OnRequestCurrentTime(struct FQualifiedFrameTime& InCurrentTime, float InPlayRate);
	void OnStartPlaying(struct FQualifiedFrameTime& InStartTime);
	void OnStopPlaying(struct FQualifiedFrameTime& InStopTime);
	void OnTick(float DeltaSeconds, float InPlayRate);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneCustomClockSource">();
	}
	static class IMovieSceneCustomClockSource* GetDefaultObj()
	{
		return GetDefaultObjImpl<IMovieSceneCustomClockSource>();
	}
};
//(alignof(IMovieSceneCustomClockSource) == 0x000008, "Wrong alignment on IMovieSceneCustomClockSource");
//(sizeof(IMovieSceneCustomClockSource) == 0x000028, "Wrong size on IMovieSceneCustomClockSource");

// Class MovieScene.MovieScenePlaybackClient
// 0x0000 (0x0028 - 0x0028)
class IMovieScenePlaybackClient final  : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieScenePlaybackClient">();
	}
	static class IMovieScenePlaybackClient* GetDefaultObj()
	{
		return GetDefaultObjImpl<IMovieScenePlaybackClient>();
	}
};
//(alignof(IMovieScenePlaybackClient) == 0x000008, "Wrong alignment on IMovieScenePlaybackClient");
//(sizeof(IMovieScenePlaybackClient) == 0x000028, "Wrong size on IMovieScenePlaybackClient");

// Class MovieScene.MovieSceneBindingOverrides
// 0x0068 (0x0090 - 0x0028)
class UMovieSceneBindingOverrides final  : public UObject
{
public:
	TArray<struct FMovieSceneBindingOverrideData> BindingData;                                       // 0x0028(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_13C4[0x58];                                    // 0x0038(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneBindingOverrides">();
	}
	static class UMovieSceneBindingOverrides* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneBindingOverrides>();
	}
};
//(alignof(UMovieSceneBindingOverrides) == 0x000008, "Wrong alignment on UMovieSceneBindingOverrides");
//(sizeof(UMovieSceneBindingOverrides) == 0x000090, "Wrong size on UMovieSceneBindingOverrides");
//(offsetof(UMovieSceneBindingOverrides, BindingData) == 0x000028, "Member 'UMovieSceneBindingOverrides::BindingData' has a wrong offset!");

// Class MovieScene.MovieSceneBindingOwnerInterface
// 0x0000 (0x0028 - 0x0028)
class IMovieSceneBindingOwnerInterface final  : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneBindingOwnerInterface">();
	}
	static class IMovieSceneBindingOwnerInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<IMovieSceneBindingOwnerInterface>();
	}
};
//(alignof(IMovieSceneBindingOwnerInterface) == 0x000008, "Wrong alignment on IMovieSceneBindingOwnerInterface");
//(sizeof(IMovieSceneBindingOwnerInterface) == 0x000028, "Wrong size on IMovieSceneBindingOwnerInterface");

// Class MovieScene.MovieSceneBuiltInEasingFunction
// 0x0010 (0x0038 - 0x0028)
class UMovieSceneBuiltInEasingFunction final  : public UObject
{
public:
	uint8                                         Pad_13C5[0x8];                                     // 0x0028(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	EMovieSceneBuiltInEasing                      Type;                                              // 0x0030(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_13C6[0x7];                                     // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneBuiltInEasingFunction">();
	}
	static class UMovieSceneBuiltInEasingFunction* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneBuiltInEasingFunction>();
	}
};
//(alignof(UMovieSceneBuiltInEasingFunction) == 0x000008, "Wrong alignment on UMovieSceneBuiltInEasingFunction");
//(sizeof(UMovieSceneBuiltInEasingFunction) == 0x000038, "Wrong size on UMovieSceneBuiltInEasingFunction");
//(offsetof(UMovieSceneBuiltInEasingFunction, Type) == 0x000030, "Member 'UMovieSceneBuiltInEasingFunction::Type' has a wrong offset!");

// Class MovieScene.MovieSceneEasingFunction
// 0x0000 (0x0028 - 0x0028)
class IMovieSceneEasingFunction final  : public IInterface
{
public:
	float OnEvaluate(float Interp) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneEasingFunction">();
	}
	static class IMovieSceneEasingFunction* GetDefaultObj()
	{
		return GetDefaultObjImpl<IMovieSceneEasingFunction>();
	}
};
//(alignof(IMovieSceneEasingFunction) == 0x000008, "Wrong alignment on IMovieSceneEasingFunction");
//(sizeof(IMovieSceneEasingFunction) == 0x000028, "Wrong size on IMovieSceneEasingFunction");

// Class MovieScene.MovieSceneFolder
// 0x0048 (0x0070 - 0x0028)
class UMovieSceneFolder final  : public UObject
{
public:
	class FName                                   FolderName;                                        // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<class UMovieSceneFolder*>              ChildFolders;                                      // 0x0030(0x0010)(ExportObject, ZeroConstructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<class UMovieSceneTrack*>               ChildMasterTracks;                                 // 0x0040(0x0010)(ExportObject, ZeroConstructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<class FString>                         ChildObjectBindingStrings;                         // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_13C7[0x10];                                    // 0x0060(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MovieSceneFolder">();
	}
	static class UMovieSceneFolder* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieSceneFolder>();
	}
};
//(alignof(UMovieSceneFolder) == 0x000008, "Wrong alignment on UMovieSceneFolder");
//(sizeof(UMovieSceneFolder) == 0x000070, "Wrong size on UMovieSceneFolder");
//(offsetof(UMovieSceneFolder, FolderName) == 0x000028, "Member 'UMovieSceneFolder::FolderName' has a wrong offset!");
//(offsetof(UMovieSceneFolder, ChildFolders) == 0x000030, "Member 'UMovieSceneFolder::ChildFolders' has a wrong offset!");
//(offsetof(UMovieSceneFolder, ChildMasterTracks) == 0x000040, "Member 'UMovieSceneFolder::ChildMasterTracks' has a wrong offset!");
//(offsetof(UMovieSceneFolder, ChildObjectBindingStrings) == 0x000050, "Member 'UMovieSceneFolder::ChildObjectBindingStrings' has a wrong offset!");

// Class MovieScene.TestMovieSceneTrack
// 0x0018 (0x0070 - 0x0058)
class UTestMovieSceneTrack final  : public UMovieSceneTrack
{
public:
	bool                                          bHighPassFilter;                                   // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_13C8[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMovieSceneSection*>             SectionArray;                                      // 0x0060(0x0010)(ExportObject, ZeroConstructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TestMovieSceneTrack">();
	}
	static class UTestMovieSceneTrack* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTestMovieSceneTrack>();
	}
};
//(alignof(UTestMovieSceneTrack) == 0x000008, "Wrong alignment on UTestMovieSceneTrack");
//(sizeof(UTestMovieSceneTrack) == 0x000070, "Wrong size on UTestMovieSceneTrack");
//(offsetof(UTestMovieSceneTrack, bHighPassFilter) == 0x000058, "Member 'UTestMovieSceneTrack::bHighPassFilter' has a wrong offset!");
//(offsetof(UTestMovieSceneTrack, SectionArray) == 0x000060, "Member 'UTestMovieSceneTrack::SectionArray' has a wrong offset!");

// Class MovieScene.TestMovieSceneSequence
// 0x0008 (0x0350 - 0x0348)
class UTestMovieSceneSequence final  : public UMovieSceneSequence
{
public:
	class UMovieScene*                            MovieScene;                                        // 0x0348(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TestMovieSceneSequence">();
	}
	static class UTestMovieSceneSequence* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTestMovieSceneSequence>();
	}
};
//(alignof(UTestMovieSceneSequence) == 0x000008, "Wrong alignment on UTestMovieSceneSequence");
//(sizeof(UTestMovieSceneSequence) == 0x000350, "Wrong size on UTestMovieSceneSequence");
//(offsetof(UTestMovieSceneSequence, MovieScene) == 0x000348, "Member 'UTestMovieSceneSequence::MovieScene' has a wrong offset!");

// Class MovieScene.TestMovieSceneSubTrack
// 0x0010 (0x0078 - 0x0068)
class UTestMovieSceneSubTrack final  : public UMovieSceneSubTrack
{
public:
	TArray<class UMovieSceneSection*>             SectionArray;                                      // 0x0068(0x0010)(ExportObject, ZeroConstructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TestMovieSceneSubTrack">();
	}
	static class UTestMovieSceneSubTrack* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTestMovieSceneSubTrack>();
	}
};
//(alignof(UTestMovieSceneSubTrack) == 0x000008, "Wrong alignment on UTestMovieSceneSubTrack");
//(sizeof(UTestMovieSceneSubTrack) == 0x000078, "Wrong size on UTestMovieSceneSubTrack");
//(offsetof(UTestMovieSceneSubTrack, SectionArray) == 0x000068, "Member 'UTestMovieSceneSubTrack::SectionArray' has a wrong offset!");

// Class MovieScene.TestMovieSceneSubSection
// 0x0000 (0x0158 - 0x0158)
class UTestMovieSceneSubSection final  : public UMovieSceneSubSection
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TestMovieSceneSubSection">();
	}
	static class UTestMovieSceneSubSection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTestMovieSceneSubSection>();
	}
};
//(alignof(UTestMovieSceneSubSection) == 0x000008, "Wrong alignment on UTestMovieSceneSubSection");
//(sizeof(UTestMovieSceneSubSection) == 0x000158, "Wrong size on UTestMovieSceneSubSection");

}

