#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GOAPNPC

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct GOAPNPC.Atom
// 0x0018 (0x0018 - 0x0000)
struct FAtom final 
{
public:
	class FString                                 Name;                                              // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bValue;                                            // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_125E[0x7];                                     // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FAtom) == 0x000008, "Wrong alignment on FAtom");
static_assert(sizeof(FAtom) == 0x000018, "Wrong size on FAtom");
static_assert(offsetof(FAtom, Name) == 0x000000, "Member 'FAtom::Name' has a wrong offset!");
static_assert(offsetof(FAtom, bValue) == 0x000010, "Member 'FAtom::bValue' has a wrong offset!");

}

