#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HDCoreUGC

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum HDCoreUGC.EHDCoreUGCTargetState
// NumValues: 0x0005
enum class EHDCoreUGCTargetState : uint8
{
	Installed                                = 0,
	Registered                               = 1,
	Loaded                                   = 2,
	Active                                   = 3,
	EHDCoreUGCTargetState_MAX                = 4,
};

// ScriptStruct HDCoreUGC.UGCPrimaryAssetSearchInfo
// 0x0018 (0x0018 - 0x0000)
struct FUGCPrimaryAssetSearchInfo final 
{
public:
	struct FPrimaryAssetType                      AssetType;                                         // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Directory;                                         // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
//(alignof(FUGCPrimaryAssetSearchInfo) == 0x000008, "Wrong alignment on FUGCPrimaryAssetSearchInfo");
//(sizeof(FUGCPrimaryAssetSearchInfo) == 0x000018, "Wrong size on FUGCPrimaryAssetSearchInfo");
//(offsetof(FUGCPrimaryAssetSearchInfo, AssetType) == 0x000000, "Member 'FUGCPrimaryAssetSearchInfo::AssetType' has a wrong offset!");
//(offsetof(FUGCPrimaryAssetSearchInfo, Directory) == 0x000008, "Member 'FUGCPrimaryAssetSearchInfo::Directory' has a wrong offset!");

// ScriptStruct HDCoreUGC.HDCoreUGCPluginStateMachineProperties
// 0x00F8 (0x00F8 - 0x0000)
struct FHDCoreUGCPluginStateMachineProperties final 
{
public:
	uint8                                         Pad_1255[0x90];                                    // 0x0000(0x0090)(Fixing Size After Last Property [ Dumper-7 ])
	class UHDCoreUGCData*                         UGCData;                                           // 0x0090(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1256[0x60];                                    // 0x0098(0x0060)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
//(alignof(FHDCoreUGCPluginStateMachineProperties) == 0x000008, "Wrong alignment on FHDCoreUGCPluginStateMachineProperties");
//(sizeof(FHDCoreUGCPluginStateMachineProperties) == 0x0000F8, "Wrong size on FHDCoreUGCPluginStateMachineProperties");
//(offsetof(FHDCoreUGCPluginStateMachineProperties, UGCData) == 0x000090, "Member 'FHDCoreUGCPluginStateMachineProperties::UGCData' has a wrong offset!");

}

